[package]
authors = ["anotherempty"]
edition = "2021"
license = "MIT"
name = "css-stacker"
repository = "https://github.com/anotherempty/css-stacker"
version = "0.1.0"

[dependencies]
clap = { version = "4.4.4", features = ["derive"] }
grass = "0.13.1"
ignore = "0.4.20"
lightningcss = { version = "1.0.0-alpha.51", features = ["browserslist"] }
thiserror = "1.0.48"
